### ISSUE TITLE
CreateHubProxy: using the generic parameter instead of interface

### ISSUE THREAD

**Issue by LukePavelka** [nenoNaninu/TypedSignalR.Client#68]
Hello, I would like to ask, why can't I use the generic parameter of the class as a generic parameter for the CreateHubProxy method?

like this 
![image](https://user-images.githubusercontent.com/76946156/191752261-58f75c31-2703-448f-ada7-5fcd473716c2.png)

**Comment by nenoNaninu** [comment]
This is because we are parsing type arguments of `CreateHubProxy` and generating code for the parsed type arguments at compile time.

Suppose you pass a type parameter such as `TService` to `CreateHubProxy`. In that case, the library cannot generate code because it cannot know which methods are defined in the `TService` type at compile time.

It is recommended to share the hub's interface between the server-side and client-side and use it as the type argument to `CreateHubProxy`.
